# Generated by Django 5.2.4 on 2025-08-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_diagnosisrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisrequest',
            name='damage_description',
            field=models.TextField(blank=True, help_text="User's description of damage"),
        ),
    ]
