# Generated by Django 5.2.4 on 2025-07-19 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('oil_change', 'Oil Change'), ('brake_change', 'Brake Change'), ('tire_rotation', 'Tire Rotation'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('mileage', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_events', to='cars.car')),
            ],
        ),
    ]
