# Generated by Django 5.2.4 on 2025-12-18 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenanceevent_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField(help_text='Date when the reminder should be sent')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('maintenance_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='maintenance.maintenanceevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reminder_date'],
            },
        ),
    ]
